/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edunova;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author WinUSER
 */
public class Prozor extends javax.swing.JFrame {

    /**
     * Creates new form Prozor
     */
    public Prozor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbliIme1 = new javax.swing.JLabel();
        lblIme2 = new javax.swing.JLabel();
        txtIme1 = new javax.swing.JTextField();
        txtIme2 = new javax.swing.JTextField();
        btnIzracunaj = new javax.swing.JButton();
        lblRjesenje = new javax.swing.JLabel();
        lblIspis = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setForeground(new java.awt.Color(255, 204, 255));
        setIconImages(null);
        getContentPane().setLayout(null);

        lbliIme1.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        lbliIme1.setForeground(new java.awt.Color(153, 0, 102));
        lbliIme1.setText("Upiši svoje ime:");
        getContentPane().add(lbliIme1);
        lbliIme1.setBounds(20, 50, 134, 42);

        lblIme2.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        lblIme2.setForeground(new java.awt.Color(153, 0, 102));
        lblIme2.setText("Upiši ime simpatije:");
        getContentPane().add(lblIme2);
        lblIme2.setBounds(20, 100, 170, 42);

        txtIme1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        txtIme1.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        txtIme1.setForeground(new java.awt.Color(153, 0, 102));
        getContentPane().add(txtIme1);
        txtIme1.setBounds(190, 40, 140, 48);

        txtIme2.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        txtIme2.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        txtIme2.setForeground(new java.awt.Color(153, 0, 102));
        getContentPane().add(txtIme2);
        txtIme2.setBounds(190, 90, 140, 48);

        btnIzracunaj.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        btnIzracunaj.setForeground(new java.awt.Color(153, 0, 102));
        btnIzracunaj.setText("IZRAČUNAJ");
        btnIzracunaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajActionPerformed(evt);
            }
        });
        getContentPane().add(btnIzracunaj);
        btnIzracunaj.setBounds(190, 140, 140, 50);

        lblRjesenje.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        lblRjesenje.setForeground(new java.awt.Color(153, 0, 102));
        lblRjesenje.setText("RJEŠENJE:");
        getContentPane().add(lblRjesenje);
        lblRjesenje.setBounds(20, 212, 150, 50);

        lblIspis.setFont(new java.awt.Font("Gabriola", 3, 36)); // NOI18N
        lblIspis.setForeground(new java.awt.Color(153, 0, 102));
        getContentPane().add(lblIspis);
        lblIspis.setBounds(40, 250, 430, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\WinUSER\\Desktop\\icon\\istockphoto-1360170364-612x612.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzracunajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajActionPerformed
     
        ArrayList<Integer> brojeviL= new ArrayList<Integer>();
					
		String ulaz1=txtIme1.getText();
		String ulaz2=txtIme2.getText();

			String ulaz = (ulaz1+ulaz2).toLowerCase();
			  
			int brojac = 0;
			for (int i = 0; i < ulaz.length(); i++)
			{
				for (int j = 0; j < ulaz.length(); j++)
				{

					if (ulaz.charAt(i) == ulaz.charAt(j))
					{
						brojac++;
					}
				}

				
				brojeviL.addAll(RastaviBroj(brojac));

				brojac = 0;
			}
						
			//System.out.println(brojeviL);
			
			if (brojeviL.size() == 1){
                            lblIspis.setText(txtIme1.getText()+ " i " +txtIme2.getText() +" vole se 1%!");//System.out.println("Volite se 1%!");
                        }
			else
			{
				//while (brojeviL.Count != 2)   
				//	brojeviL = Kalkulator(brojeviL);
				brojeviL = RekurzivniKalkulator(brojeviL);  //Ovde se poziva rekurzivna funkcija RF bez while petlje
				//System.out.print("Volite se ");
				String izlaz="";
                                for (int i : brojeviL)
					izlaz+=Integer.toString(i);//System.out.print(b);
			lblIspis.setText(txtIme1.getText() + " i " + txtIme2.getText() + " vole se " + izlaz + "%!");}
                         

		
	}

	static ArrayList<Integer> RastaviBroj(int broj)
	{
		ArrayList<Integer> podLista = new ArrayList<Integer>();
		int ost;
		int br = broj;
		while (br != 0)
		{
			ost = br % 10;
			podLista.add(ost);
			br /= 10;
		}
		 Collections.reverse(podLista);
		return podLista;
	}
	
	
	static ArrayList<Integer> RekurzivniKalkulator(ArrayList<Integer> lBr)
    {
			
		ArrayList<Integer> novaBrL = new ArrayList<Integer>();

		if (lBr.size() == 2) return lBr;
		else
		{
			int i = 0;
			int j = lBr.size() - 1;
			int k;
			int broj;
			for (k = 0; k < lBr.size() / 2; k++)
			{
				broj = lBr.get(i) + lBr.get(j);

				novaBrL.addAll(RastaviBroj(broj));

				i++;
				j--;
			}
			if (lBr.size() % 2 == 1)
			{
				novaBrL.add(lBr.get(i));
			}

			return RekurzivniKalkulator(novaBrL);
		}
               
    }//GEN-LAST:event_btnIzracunajActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzracunaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIme2;
    private javax.swing.JLabel lblIspis;
    private javax.swing.JLabel lblRjesenje;
    private javax.swing.JLabel lbliIme1;
    private javax.swing.JTextField txtIme1;
    private javax.swing.JTextField txtIme2;
    // End of variables declaration//GEN-END:variables
}
